### ISSUE TITLE
ASCII characters

### ISSUE THREAD

**Issue by Vilican** [Fireflies/MaintenanceMode#5]
Could you add support for ASCII characters? It allows only English alphabet.

**Comment by Fireflies** [comment]
Hello there.

This resource is currently being maintained by @ElieTGM, if you could please visit [this][spigot-thread] spigot thread and post your request there they will be more likely to see it. :smile: 

I may be producing a rewrite soon though if it's of interest.

[spigot-thread]: https://www.spigotmc.org/resources/maintenancemode.2548/

**Comment by Vilican** [comment]
Ok, thanks.
